image: gitpod/workspace-full

tasks:
  - before: sdk install java 17.0.4.1-tem < /dev/null
    init: cd backend/sentry-gitpod-demo && ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run backend

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-spring-initializr

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both