image: gitpod/workspace-full

tasks:
  - before: sdk install java 17.0.4.1-tem < /dev/null
    init: cd backend/sentry-gitpod-demo && ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Backend
  - init: cd frontend/my-app && npm i
    command: npm start
    name: Frontend

ports:
  - port: 8080
    onOpen: ignore
    description: Backend
  - port: 3000
    onOpen: open-preview
    description: Frontend

vscode:
  extensions:
    - vscjava.vscode-spring-initializr

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both